seed_everything: null
trainer:
  logger: true
  checkpoint_callback: null
  enable_checkpointing: true
  callbacks: null
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  process_position: 0
  num_nodes: 1
  num_processes: null
  devices: null
  gpus: null
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  flush_logs_every_n_steps: null
  log_every_n_steps: 50
  accelerator: null
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  prepare_data_per_node: null
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
  terminate_on_nan: null
model:
  fx: null
  num_bands: null
  param_range: null
  cond_feat: null
  tracker: false
  rate: 22050
  total_num_bands: null
  fft_size: 1024
  hop_size: 256
  audiologs: 4
  loss_weights:
  - 1.0
  - 1.0
  mrstft_fft:
  - 64
  - 128
  - 256
  - 512
  - 1024
  - 2048
  mrstft_hop:
  - 16
  - 32
  - 64
  - 128
  - 256
  - 512
  learning_rate: 0.001
  out_of_domain: false
  spectro_power: 2
  mel_spectro: true
  mel_num_bands: 128
  loss_stamps:
  reverb: false
data:
  clean_dir: null
  processed_dir: null
  out_of_domain_dir: null
  batch_size: 32
  num_workers: 4
  out_of_domain: false
  seed: null
  reverb: false
  train_transforms: null
  val_transforms: null
  test_transforms: null
  dims: null
ckpt_path: null
